export const SET_USERS_LIST = '[USERS] SET_USERS_LIST';
export const SET_IS_FETCHING_USERS_LIST_TRUE = '[USERS] SET_IS_FETCHING_USERS_LIST_TRUE';
export const SET_IS_FETCHING_USERS_LIST_FALSE = '[USERS] SET_IS_FETCHING_USERS_LIST_FALSE';
export const SHOW_EDIT_USER_MODAL = '[USERS] SHOW_EDIT_USER_MODAL';
export const HIDE_EDIT_USER_MODAL = '[USERS] HIDE_EDIT_USER_MODAL';
export const RESET_APP_REDUCER = '[USERS] RESET_APP_REDUCER';
