//users
export const SET_USERS_LIST = '[USERS] SET_USERS_LIST';
export const SET_IS_FETCHING_USERS_LIST_TRUE = '[USERS] SET_IS_FETCHING_USERS_LIST_TRUE';
export const SET_IS_FETCHING_USERS_LIST_FALSE = '[USERS] SET_IS_FETCHING_USERS_LIST_FALSE';
export const SHOW_EDIT_USER_MODAL = '[USERS] SHOW_EDIT_USER_MODAL';
export const HIDE_EDIT_USER_MODAL = '[USERS] HIDE_EDIT_USER_MODAL';
export const RESET_APP_REDUCER = '[USERS] RESET_APP_REDUCER';

//edit user form
export const SET_EDIT_USER_FORM_NAME_PROPERTIES = '[EDIT_USER] SET_EDIT_USER_FORM_NAME_PROPERTIES';
export const SET_EDIT_USER_FORM_EMAIL_PROPERTIES =
	'[EDIT_USER] SET_EDIT_USER_FORM_EMAIL_PROPERTIES';
export const SET_EDIT_USER_FORM_CITY_PROPERTIES = '[EDIT_USER] SET_EDIT_USER_FORM_CITY_PROPERTIES';
export const SET_EDIT_USER_FORM_PHONE_PROPERTIES =
	'[EDIT_USER] SET_EDIT_USER_FORM_PHONE_PROPERTIES';
export const SET_EDIT_USER_FORM_WEBSITE_PROPERTIES =
	'[EDIT_USER] SET_EDIT_USER_FORM_WEBSITE_PROPERTIES';
export const SET_EDIT_USER_FORM_COMPANY_NAME_PROPERTIES =
	'[EDIT_USER] SET_EDIT_USER_FORM_COMPANY_NAME_PROPERTIES';
export const RESET_EDIT_USER_FORM = '[EDIT_USER] RESET_EDIT_USER_FORM';
