export const SET_USERS_LIST = '[APP] SET_USERS_LIST';
export const SET_IS_FETCHING_USERS_LIST_TRUE = '[APP] SET_IS_FETCHING_USERS_LIST_TRUE';
export const SET_IS_FETCHING_USERS_LIST_FALSE = '[APP] SET_IS_FETCHING_USERS_LIST_FALSE';
export const SHOW_EDIT_USER_MODAL = '[APP] SHOW_EDIT_USER_MODAL';
export const HIDE_EDIT_USER_MODAL = '[APP] HIDE_EDIT_USER_MODAL';
export const RESET_APP_REDUCER = '[APP] RESET_APP_REDUCER';
